[package]
name = "sparsnas"
version = "0.1.0"
authors = ["Daniel Svensson"]
edition = "2018"

[dependencies]
cc1101 = { git = "https://github.com/dsvensson/cc1101", rev = "master" }
byteorder = "1.2.2"
rppal = { version = "0.11.3", features = ["hal"] }
